### ISSUE TITLE
Voice instruction is not working if 'shapeFormat = .geoJSON'.

### ISSUE THREAD

**Issue by arshadtp** [mapbox/mapbox-navigation-ios#2298] opened 2020-01-07 13:46 UTC
**Mapbox Navigation SDK version:  0.38.1**

>   - Mapbox-iOS-SDK (5.5.0)
>   - MapboxCoreNavigation (0.38.1):
>     - MapboxDirections.swift (~> 0.30.0)
>     - MapboxMobileEvents (~> 0.9.5)
>     - MapboxNavigationNative (~> 6.2.1)
>     - Turf (~> 0.3.0)
>   - MapboxDirections.swift (0.30.0):
>     - Polyline (~> 4.2)
>   - MapboxGeocoder.swift (0.12.0)
>   - MapboxMobileEvents (0.9.5)
>   - MapboxNavigation (0.38.1):
>     - Mapbox-iOS-SDK (~> 5.2)
>     - MapboxCoreNavigation (= 0.38.1)
>     - MapboxSpeech (~> 0.1.0)
>     - Solar (~> 2.1)
>   - MapboxNavigationNative (6.2.1)
>   - MapboxSpeech (0.1.1)

Voice instructions are not working for me in the latest SDK. It is working fine in MapboxNavigation version 0.37.0.

Please find the code part below,

   ```
 let origin = CLLocationCoordinate2DMake(37.77440680146262, -122.43539772352648)
    let destination = CLLocationCoordinate2DMake(37.76556957793795, -122.42409811526268)
    let options = NavigationRouteOptions(coordinates: [origin, destination])
    options.shapeFormat = .geoJSON
    Directions.shared.calculate(options) { (waypoints, routes, error) in
        guard let route = routes?.first, error == nil else {
            print(error!.localizedDescription)
            return
        }

        let navigationService = MapboxNavigationService(route: route, simulating: .always)
        let navigationOptions = NavigationOptions(navigationService: navigationService)
        let navigationViewController = NavigationViewController(for: route, options: navigationOptions)
        navigationViewController.modalPresentationStyle = .fullScreen

        self.present(navigationViewController, animated: true, completion: nil)
    }
```

It is working fine if I removed the line  `options.shapeFormat = .geoJSON` (working fine with default shape format: .polyline6).

Any help is greatly appreciated.

**Comment by 1ec5** [comment] 2020-01-07 21:17
This is a duplicate of #2125. Using the default shape format, `polyline6`, should be a suitable workaround for now. It only means the API sends the SDK the route shape in a more efficient format, but you can work with the same coordinate data regardless.

**Closed by 1ec5** 2020-01-07 21:17 UTC
