### ISSUE TITLE
Add exit information to UI 

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#401] opened 2017-07-18 23:51 UTC
Soon, we'll have access to exit information available. Let's figure out a way we can squeeze this into the top maneuver bar.

Something like:

```
           --------
San Jose  |  47B ↗️ |
           --------
```

The crux of this will be figuring out how we handle a case where we have 1) name(s) 2) destination(s) 3) exit(s).

/cc @1ec5 @frederoni @mayagao

**Comment by 1ec5** [comment] 2017-07-19 07:30
Duplicate of #337.

**Closed by 1ec5** 2017-07-19 07:30 UTC
