### ISSUE TITLE
Can't use react-native-mapbox-gl and MapboxNavigation with CocoaPods

### ISSUE THREAD

**Issue by ClementPF** [mapbox/mapbox-navigation-ios#2016] opened 2019-03-11 22:32 UTC
**Mapbox Navigation SDK version:** 0.29.1
**react-native-mapbox-gl**  6.1.3

Hello, I'm having an issue trying to use the Mapbox iOS Navigation along with the react-native-mapbox-gl module with CocoaPods.

Trying to use them together throws
`[!] The 'Pods-abcd' target has frameworks with conflicting names: mapbox.framework.`

### Steps to reproduce:

1. `react-native init abcd`
2. `cd abcd && npm install @mapbox/react-native-mapbox-gl --save`
3. `cd ios && touch Podfile`
4. Copy the following into the Podfile located abcd/ios/Podfile
```
platform :ios, '9.0'

target 'abcd' do

  use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'RCTImage'
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
  pod 'MapboxNavigation', '~> 0.29.0'
end
```
5. `pod install`
6. Notice `[!] The 'Pods-abcd' target has frameworks with conflicting names: mapbox.framework.` preventing the creation of the .xcworkspace

### Expected behavior:
The two SDKs should be able to be used together.

Thanks !

**Comment by 1ec5** [comment] 2019-03-13 14:49
RNMBGL v6._x_ depends on a very old version of the iOS map SDK. v7._x_ will likely be based on a compatible version. It’s being developed in nitaliano/react-native-mapbox-gl#1377; see https://github.com/nitaliano/react-native-mapbox-gl/issues/1238#issuecomment-461585880 for the latest progress update. I’m closing this issue because there’s nothing the navigation SDK project can do about a downstream project’s dependency management.

**Closed by 1ec5** 2019-03-13 14:49 UTC

**Comment by 1ec5** [comment] 2019-03-13 14:55
Additionally, the incompatibility reported by CocoaPods is caused by the fact that RNMBGL is [distributed as Mapbox.framework](https://github.com/nitaliano/react-native-mapbox-gl/blob/e4b825275988e9054112139af1f31ad015fa4cf0/react-native-mapbox-gl.podspec#L16), which happens to be the same bundle name that the iOS map SDK uses. CocoaPods requires each framework embedded within an iOS application target to have a distinct name. (This is a best practice for iOS applications in general.) nitaliano/react-native-mapbox-gl#1535 is sufficient for tracking this issue.

**Comment by Jackyaung** [comment] 2019-06-13 14:24
I still didn't get how to solve the problem, even I checked all the links above.

**Comment by DavidKHahn** [comment] 2019-07-03 00:46
@1ec5 is there any update to this upcoming update? Currently trying to bridge together mapbox-react-native + navigation into a single application.  Any leads would be appreciated.

**Comment by martinezguillaume** [comment] 2019-07-03 14:26
I'm searching too how to implement mapbox navigation sdk into react-native, if someone has some advice

**Comment by clarodanesh** [comment] 2019-07-10 22:43
You should check this repository out

https://github.com/SRHealth/react-native-mapbox-navigation

**Comment by DavidKHahn** [comment] 2019-07-11 00:00
One of the ways would be to create a bridge using objective C allowing
react-native's built-in Native Modules. You should check out:
https://facebook.github.io/react-native/docs/native-modules-ios for more
information.  This is possible however a bit tricky.

**Comment by DavidKHahn** [comment] 2019-07-19 05:19
@clarodanesh does this work for with mapbox + navigation? seems like the documentation is non-existant can you state how the package/properties are used?

**Comment by deriksadiki** [comment] 2019-10-09 11:47
@clarodanesh i checked out your link and it is working on my device after cloning it but how do i use it on a different project?

**Comment by Davidvision** [comment] 2019-11-16 12:12
I’m trying to do exactly the same, any advice on how to implement it would be greatly appreciated.

**Comment by iutin** [comment] 2019-11-22 10:24
> @clarodanesh i checked out your link and it is working on my device after cloning it but how do i use it on a different project?

Hi! Do you have any progress? I have the same question now(

**Comment by deriksadiki** [comment] 2019-11-22 11:28
nope no progress so far, I ended up creating a custom navigation but its not that brilliant since the map doesn't move according to the path (road) , if the road is a curve, the pin still moves straight, you have to rotate the map manually

**Comment by clarodanesh** [comment] 2019-11-22 11:30
@iutin @deriksadiki hi guys, Im in the same situation, havent implemented this in another project, only used the cloned repository.

**Comment by adhendo** [comment] 2020-10-30 01:51
@clarodanesh @deriksadiki or anyone else, do you have a link to https://github.com/SRHealth/react-native-mapbox-navigation repository? it seems to be missing now...

**Comment by deriksadiki** [comment] 2020-10-30 09:15
i do not have it, maybe he deleted the repo

**Comment by deriksadiki** [comment] 2020-10-30 09:16
> @clarodanesh @deriksadiki or anyone else, do you have a link to https://github.com/SRHealth/react-native-mapbox-navigation repository? it seems to be missing now...

i do not have it, maybe he deleted the repo

**Comment by clarodanesh** [comment] 2020-10-30 22:14
> @clarodanesh @deriksadiki or anyone else, do you have a link to https://github.com/SRHealth/react-native-mapbox-navigation repository? it seems to be missing now...
> 

Hi, no unfortunately, it seems to have been deleted now. I dont have a downloaded or cloned copy either.
