### ISSUE TITLE
[Bug]: New crashed app issue when upgrade mapbox navigation sdk to 2.10.0

### ISSUE THREAD

**Issue by santoso8118** [mapbox/mapbox-navigation-ios#4451] opened 2023-05-11 06:15 UTC
### Mapbox Navigation SDK version

2.10.0

### Steps to reproduce

We got crashed log as below but can not find a clear steps to reproduce:

```
Crashed: com.apple.main-thread
0  MyApp                         0xde58d0 NavigationMapView.updateIntersectionAnnotations(with:) + 4377303248 (<compiler-generated>:4377303248)
1  MyApp                         0xd31490 CarPlayNavigationViewController.progressDidChange(_:) + 4376564880 (<compiler-generated>:4376564880)
2  MyApp                         0xd315e0 @objc CarPlayNavigationViewController.progressDidChange(_:) + 4376565216 (<compiler-generated>:4376565216)
3  CoreFoundation                 0x373b4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
4  CoreFoundation                 0xde444 ___CFXRegistrationPost_block_invoke + 88
5  CoreFoundation                 0xc16f4 _CFXRegistrationPost + 440
6  CoreFoundation                 0x4b9b8 _CFXNotificationPost + 704
7  Foundation                     0x5cd0c -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
8  MyApp                         0x1027610 RouteController.update(progress:status:with:rawLocation:upcomingRouteAlerts:mapMatchingResult:routeShapeIndex:) + 4379670032 (<compiler-generated>:4379670032)
9  MyApp                         0x1025464 RouteController.update(to:) + 4379661412 (<compiler-generated>:4379661412)
10 MyApp                         0x1024d70 RouteController.navigationStatusDidChange(_:) + 4379659632 (<compiler-generated>:4379659632)
11 MyApp                         0x1024de4 @objc RouteController.navigationStatusDidChange(_:) + 4379659748 (<compiler-generated>:4379659748)
12 CoreFoundation                 0x373b4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
13 CoreFoundation                 0xde444 ___CFXRegistrationPost_block_invoke + 88
14 CoreFoundation                 0xc16f4 _CFXRegistrationPost + 440
15 CoreFoundation                 0x4b9b8 _CFXNotificationPost + 704
16 Foundation                     0x5cd0c -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
17 MyApp                         0xfad8f0 NavigatorStatusObserver.onStatus(for:status:) + 4379171056 (<compiler-generated>:4379171056)
18 MyApp                         0xfad990 @objc NavigatorStatusObserver.onStatus(for:status:) + 4379171216 (<compiler-generated>:4379171216)
19 MapboxNavigationNative         0x43450 (Missing UUID ce7f810247bc384390faaf3f4eaff9b5)
20 MapboxNavigationNative         0x323cf8 (Missing UUID ce7f810247bc384390faaf3f4eaff9b5)
21 MapboxCommon                   0x440e0 mapbox::common::DarwinRunLoop::Source::perform(void*) + 32
22 CoreFoundation                 0xd5f24 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
23 CoreFoundation                 0xe22fc __CFRunLoopDoSource0 + 176
24 CoreFoundation                 0x66220 __CFRunLoopDoSources0 + 340
25 CoreFoundation                 0x7bb7c __CFRunLoopRun + 836
26 CoreFoundation                 0x80eb0 CFRunLoopRunSpecific + 612
27 GraphicsServices               0x1368 GSEventRunModal + 164
28 UIKitCore                      0x3a1668 -[UIApplication _run] + 888
29 UIKitCore                      0x3a12cc UIApplicationMain + 340
30 MyApp                         0x13874 main + 45 (AppDelegate.swift:45)
31 ???                            0x1bf1e0960 (Missing)
```

### Expected behavior

App not crashed

### Actual behavior

App got crashed

### Is this a one-time issue or a repeatable issue?

one-time

**Comment by kried** [comment] 2023-05-29 22:13
Hi @santoso8118 

Please update to v2.11.0 or newer. The possible crash caused by incorrect indexes was fixed in #4314 in [v2.11.0](https://github.com/mapbox/mapbox-navigation-ios/blob/main/CHANGELOG.md#v2110).

**Closed** 2023-06-02 09:17 UTC
Labels: bug
