### ISSUE TITLE
Missing Description in Jazzy-Generated API Docs

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-navigation-ios#1945] opened 2019-01-24 16:30 UTC
A large amount of methods and attributes that appear on https://docs.mapbox.com/ios/api/navigation/ are missing descriptions from the drop down menus. Here's a screenshot:

<img width="697" alt="screen shot 2019-01-24 at 11 23 20 am" src="https://user-images.githubusercontent.com/16272584/51692444-efe30c00-1fca-11e9-9b4a-f2ffbb4cd0c0.png">

This seems to be a problem with how the Jazzy generated docs are working because the source files clearly have content that should be populating:

https://github.com/mapbox/mapbox-navigation-ios/blob/cb4533a32dc0e80e4aa021fce922d08396e4398b/MapboxCoreNavigation/NavigationServiceDelegate.swift#L6-L14

It would be helpful to have this resolved soon so that the API docs have full, descriptive documentation for these methods.

**Comment by 1ec5** [comment] 2019-01-25 00:41
Duplicate of #1795.

**Closed by 1ec5** 2019-01-25 00:41 UTC
Labels: documentation
