### ISSUE TITLE
wrong german translation

### ISSUE THREAD

**Issue by pintonos** [mapbox/mapbox-navigation-ios#2219] opened 2019-08-28 17:10 UTC
Although i used the **walking** profile identifier, it sometimes says “Fahren sie…” (drive), instead of “Gehen sie…” (move). I think this is a wrong translation or the translation is not dependent of the given profile identifier.

**Comment by 1ec5** [comment] 2019-08-29 06:51
Duplicate of #2203.

**Closed by 1ec5** 2019-08-29 06:51 UTC
