### ISSUE TITLE
Possibility to specify *elevation* in directions request.

### ISSUE THREAD

**Issue by kuchmiyalex** [mapbox/mapbox-navigation-ios#486] opened 2017-08-14 07:47 UTC
Building an app for indoor routing and facing an issue that we can't specify *floor* we need to go, start and destination waypoints are created just by coordinates.
Is it possible to add optional **level** param to tell API that user wants to go to certain floor, not just coordinate?

**Comment by bsudekum** [comment] 2017-08-14 15:37
Hi @kuchmiyalex,

Currently adding an `elevation` query param is not supported nor on our roadmap. What is the use case you're looking to solve? By the use of "level", it sounds like you're trying to do indoor mapping? If however you're looking to solving the overlapping-highway-issue, we're looking into this.

**Comment by kuchmiyalex** [comment] 2017-08-14 22:28
@bsudekum Thanks for response!
We're trying to build multi-floor parking navigation above mapbox and this roadblock looks related to overlapping-highway-issue. I just can't specify which floor I'm interested if routes are overlapping.

**Comment by 1ec5** [comment] 2017-10-02 21:21
I don’t think we have an issue in this repository regarding “overlapping highways”. The problem is basically that, if the user is located on an overpass or underpass, the Directions API has little idea which road they’re on. We pass the user’s heading to the Directions API to help it filter out unlikely candidates, but that approach fails on double-decker highways and the like.

Multi-floor parking garages can be tagged in OpenStreetMap as `highway=service` `service=parking_aisle` [`level=#`](https://wiki.openstreetmap.org/wiki/Key:level) ways, but OSRM doesn’t currently make use of the `level` or `ele` tags. I’d suggest opening an issue in the [osrm-backend](https://github.com/Project-OSRM/osrm-backend/) repository explaining your use case more fully. I’ll close this issue since the eventual implementation would have no impact on the navigation SDK. (Any elevation option would be exposed on RouteOptions in MapboxDirections.swift, not NavigationViewController in this project.)

**Closed by 1ec5** 2017-10-02 21:21 UTC
