### ISSUE TITLE
Polly pronounces “S” in ref as “South”

### ISSUE THREAD

**Issue by freenerd** [mapbox/mapbox-navigation-ios#286] opened 2017-06-19 12:57 UTC
In  Saxony, Germany there are roads like `S 81`. [Wikipedia has a list](https://de.wikipedia.org/wiki/Liste_der_Staatsstra%C3%9Fen_in_Sachsen) and here are some on the [map](http://map.project-osrm.org/?z=14&center=51.228899%2C13.558288&loc=51.234192%2C13.540306&loc=51.233279%2C13.557472&hl=en&alt=0
). 

Right now these are extended to `South 81` instead of staying `S 81` (via [this code](https://github.com/mapbox/mapbox-navigation-ios/blob/5d78f52e52d2e1e847336890a44bfaae6505f653/MapboxNavigation/Resources/Base.lproj/Abbreviations.csv.plist#L73
)).

This is definitely a fringe problem (only 5000 km of roads in Germany have this abbreviation) but highlights issues with using abbreviation expansion of one place in another.

/cc @1ec5 @bsudekum

**Comment by 1ec5** [comment] 2017-06-20 05:37
Do you have a screenshot of the problem? Abbreviations.plist is used for _abbreviating_, not for expanding abbreviations, and only on the road name (after any `ref` has been stripped away). The expected behavior is that “South” in a `name` tag becomes “S”, but “S” in a `ref` tag should remain unchanged.

On the other hand, there is a geographical issue with Shields.plist, where [`CA`](https://github.com/mapbox/mapbox-navigation-ios/blob/1677c6479a2a293172a4a4d1e3ea45e5c1e3707b/MapboxNavigation/Resources/Shields.plist#L29-L30) may denote California or Cantabría, or [`NH`](https://github.com/mapbox/mapbox-navigation-ios/blob/1677c6479a2a293172a4a4d1e3ea45e5c1e3707b/MapboxNavigation/Resources/Shields.plist#L83-L84) New Hampshire or National Highway (e.g., in India), or [`CO`](https://github.com/mapbox/mapbox-navigation-ios/blob/1677c6479a2a293172a4a4d1e3ea45e5c1e3707b/MapboxNavigation/Resources/Shields.plist#L31-L32) Colorado or “county”. Unfortunately, there isn’t a better way to distinguish shields internationally until either Project-OSRM/osrm-backend#482 or Project-OSRM/osrm-backend#333 is implemented.

**Comment by freenerd** [comment] 2017-06-21 10:21
I'm pretty sure the voice instruction said "South 94"

![image uploaded from ios 17](https://user-images.githubusercontent.com/25713/27379562-fa05e500-567b-11e7-896b-3239a99b63a9.jpg)

http://map.project-osrm.org/?z=17&center=51.380530%2C14.079157&loc=51.379536%2C14.076104&loc=51.378826%2C14.082263&hl=en&alt=0

**Comment by 1ec5** [comment] 2017-06-21 10:25
That application uses Amazon Polly. It’s likely that Polly interprets “S” as “South” in this context. We can avoid that and similar issues by surrounding the ref in a `<say-as>` tag that spells out the ref.

**Comment by 1ec5** [comment] 2017-06-21 10:27
We’re already [marking up the ref](https://github.com/mapbox/mapbox-navigation-ios/blob/6988db6428a9173361876fe6417d968496ea1ba1/MapboxNavigation/RouteVoiceController.swift#L261) to be interpreted as an address. I wonder if there’s a more appropriate interpretation here.

/cc @bsudekum

**Comment by 1ec5** [comment] 2017-07-05 17:24
> On the other hand, there is a geographical issue with Shields.plist

→ #334

**Comment by 1ec5** [comment] 2017-07-16 04:23
@bhousel pointed out that, because of how many [county roads in New Jersey](https://en.wikipedia.org/wiki/County_routes_in_New_Jersey) are currently tagged `ref=(510)` instead of `ref=CR 510` – [long story](https://lists.openstreetmap.org/pipermail/talk-us/2010-May/003406.html) – Polly pronounces them e.g. “open-parenthesis 5-1-0 close-parenthesis”. Those `ref` tags will be fixed in short order, but some roads in other regions have legitimate parentheses, like the [A1(M) motorway](https://en.wikipedia.org/wiki/A1%28M%29_motorway) in England.

**Comment by 1ec5** [comment] 2017-08-25 08:57
The “S” as “South” case was fixed in mapbox/mapbox-navigation-ios#509. Not sure whether “A1(M)” still gets pronounced as “a one open-parenthesis em close-parenthesis”.

**Comment by 1ec5** [comment] 2017-08-30 18:42
#552 should’ve fixed the parenthesis case as well.

**Closed by 1ec5** 2017-08-30 18:42 UTC
