### ISSUE TITLE
Building highlighting no longer works after updating to Mapbox Maps `v10.0.0-beta.21`.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3065] opened 2021-06-09 14:54 UTC
**Mapbox Navigation SDK version:** [PR](https://github.com/mapbox/mapbox-navigation-ios/pull/3039)

After updating to Mapbox Maps `v10.0.0-beta.21` building highlighting no longer works. Building will be highlighted in case if destination was requested in preview mode, but during active guidance navigation it's no longer possible to highlight the building.

**Comment by ShanMa1991** [comment] 2021-06-15 16:50
I've created a ticket in the internal repo of `MapboxMaps`. The problem is caused by the feature query process to find the feature identifier always return `nil` during turn-by-turn navigation. So the building could not be highlighted.

**Comment by ShanMa1991** [comment] 2021-06-30 19:49
I tried to create a `CGRect` instead of a `CGPoint`, it's still not working as following. The problem should be related with the feature query process during the camera change, and how the `CGPoint` converted from the `Coordinate2D`.

```
            let southWestCoordinate = coordinate.coordinate(at: 10, facing: 270)
            let northEastCoordinate = coordinate.coordinate(at: 10, facing: 90)
            let corrdinateBounds = CoordinateBounds(southwest: southWestCoordinate, northeast: northEastCoordinate)
            let screenBox = mapView.mapboxMap.rect(for: corrdinateBounds)
            
            mapView.mapboxMap.queryRenderedFeatures(in: screenBox,
                                                    options: options,
                                                    completion: { [weak self] result in
                                                        guard let _ = self else { return }
                                                        if case .success(let queriedFeatures) = result {
                                                            if let identifier = queriedFeatures.first?.feature.identifier as? Int64 {
                                                                foundBuildingIds.insert(identifier)
                                                            }
                                                            group.leave()
                                                        }
                                                    })
```

**Comment by ShanMa1991** [comment] 2021-07-14 22:10
The issue seems to be fixed in the Maps side or the GL-JS side. Now it could no longer be produced.

**Closed by ShanMa1991** 2021-07-14 22:10 UTC
Labels: - bug, UI, blocked
