### ISSUE TITLE
Customized milestone triggers + notifications

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#325] opened 2017-06-30 18:01 UTC
iOS should implement the equivalent of Android's Milestone feature to expand on our current AlertLevels: https://github.com/mapbox/mapbox-navigation-android/pull/84

> This PR removes the alert levels in favor of a more robust system called milestones. Milestones are more abstract, use the dsl pattern, offering some of the features listed below:
> * Easier readability
> * Besides the default, developers can create their own milestones
> * Customize what exactly triggers the milestone/alert

cc @bsudekum @cammace @1ec5

**Comment by 1ec5** [comment] 2017-07-01 00:12
Duplicate of #224. For what it’s worth, I think the DSL and Builder patterns are a poor fit for Objective-C and Swift, so we’ll either need to find an analogous declarative pattern or (more likely) rely on callbacks.

**Closed by 1ec5** 2017-07-01 00:12 UTC
