### ISSUE TITLE
How to access various map features

### ISSUE THREAD

**Issue by TCOA** [mapbox/mapbox-navigation-ios#218] opened 2017-05-11 15:56 UTC
documentation on this is not clear (for a new-to-xcode person like myself) and I could really use the 'newbie' version of how to access the following:

1. 'Arrived' alert - I placed a comment on https://github.com/mapbox/mapbox-navigation-ios/issues/126 as it relates to the alerts - perhaps it is best to ask it here(?) - though it is a 'critical' thing for me to access for completing my app.

2. access to/ removal of 'Cancel' button - while it is great that you put a Cancel button on the view, it doesn't do what my 'Cancel' should do and I need to avoid yours!  I placed an icon over the 'Cancel' you have, though in our testing, we found it possible to 'flip up' the bottom row and see the turn-by-turn directions (another cool, undocumented feature....) - that is great, though the 'Cancel' shows up again and, should our users click it, well........  

What I would really like here is to know what you are doing in the 'Cancel' to remove the view and how you expect us to 'recover' from that (i.e., what a typical use case would be from what you designed) - the documentation states "routeControllerDidCancelNavigation: Fired when the user taps Cancel. You are responsible for dismissing the UI", though no example of this (so I'm a bit lost on how to know this fired...) - all we get is a blank page.....  (sorry, my newness is showing a lot here, I know, but all your other examples are very clear.....)

3. 'zoom to route' - I can't seem to find what Mapbox calls this (I thought it was 'flyto', but that doesn't seem right....) - anyway, it is where the entire route is shown on the screen, instead of a pre-set zoom level.  I have that in my spec to begin the view there - then (as you have it with another cool, yet undocumented feature.....), the user can 'two-finger' zoom in/out to adjust if/as they like.  But, how do I set this originally?

4. compassView - I have been asked to provide a 'clickable' method to switch from 'due north' to 'direction I am going'.  I know Mapbox has this feature, with 'compassView' https://www.mapbox.com/ios-sdk/api/3.5.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)compassView yet don't know how to add this.  Note: in 'playing' with the view, we found that it is possible to 'flick' the navigation box on the top and it appears this may be doing this, however, in our tests, we are not getting the desired results (could be a location simulator issue -not sure if we are doing something wrong in our testing or if something else) - as there is no documentation on what this should be doing, we are having to reverse-engineer what is likely another cool feature..........

Thanks for all the work on this library - it does have a lot of great features, we just need to know what they are and how to access the ones we need to link into!

**Comment by bsudekum** [comment] 2017-05-11 16:12
@TCOA our view on this subject is that we provide essentially 2 libraries here; the MapboxCoreNavigation and MapboxNavigaiton. MapboxCoreNavigation contains the core routing logic- is the user on the route, how much time do they have left, etc. MapboxNavigaiton contains everything else, most notably the UI. If you go with MapboxNavigaiton you get the kitchen sink but you only customize it so much. If you need a custom UI, you'll have to build it from the ground up with MapboxCoreNavigation. 

That said, I think some of your bullet points above are valid. I'll go through them one by one.

1. This should be accessible by listening on [`RouteControllerAlertLevelDidChange`](https://github.com/mapbox/mapbox-navigation-ios/blob/master/Examples/Swift/ViewController.swift#L70) and the parsing out the alert level off the route progress from this notification. [See the example code here](https://github.com/mapbox/mapbox-navigation-ios/blob/master/Examples/Swift/ViewController.swift#L81-L86).
2. I think this is out of scope for MapboxNavigaiton and warrants the use of MapboxCoreNavigaiton to build your custom UI from scratch.
3. This is in master but not yet in a release, see https://github.com/mapbox/mapbox-navigation-ios/pull/106
4. We should add this as an option 👍

**Comment by 1ec5** [comment] 2017-05-11 16:40
> You are responsible for dismissing the UI

You’re only responsible for dismissing the UI if you implement `NavigationViewControllerDelegate.navigationViewControllerDidCancelNavigation(_:)`. If you omit that method, the SDK will handle dismissing the UI for you.

If you’re using a storyboard, this would be the appropriate place to trigger an [unwind segue](https://developer.apple.com/library/content/technotes/tn2298/_index.html) to some other view controller in your application. Otherwise, you could pop the current view controller off the stack, for example using `dismiss(animated: true, completion: nil)`.

> I have been asked to provide a 'clickable' method to switch from 'due north' to 'direction I am going'.

The map does have a compass view, but the turn banner is obscuring it due to a regression in the map SDK: mapbox/mapbox-gl-native#6954.

**Comment by TCOA** [comment] 2017-05-11 17:04
Thanks for super-fast responses!

1. I am listening on there....
` let center = NotificationCenter.default
            center.addObserver(forName: NSNotification.Name(rawValue: "RouteControllerProgressDidChange"), object: nil, queue: nil) { notification in
                print("NOTIFICATION CENTER - RouteControllerProgressDidChange: \(notification.name): \(notification.userInfo ?? [:])")
            }
            center.addObserver(forName: NSNotification.Name(rawValue: "RouteControllerAlertLevelDidChange"), object: nil, queue: nil) { notification in
                print("NOTIFICATION CENTER - RouteControllerAlertLevelDidChange: \(notification.name): \(notification.userInfo ?? [:]) \(notification.description)")
            }
            center.addObserver(forName: NSNotification.Name(rawValue: "RouteControllerProgressDidChangeNotificationProgressKey"), object: nil, queue: nil) { notification in
                print("NOTIFICATION CENTER - RouteControllerProgressDidChangeNotificationProgressKey: \(notification.name): \(notification.userInfo ?? [:])  \(notification.description )")
            }`

and get great data, though I was expecting (at minimum, hoping!) for 
`Alert levels

Alert levels indicate the type of announcement that should be given. The enum types available are:

none
depart - Emitted while departing origin
low - Emitted directly after completing the maneuver
medium - Emitted when the user has 70 seconds remaining on the route.
high - Emitted when the user has 15 seconds remaining on the route.
arrive - Emitted when the user arrives at destination
 `

What I get from the referenced RouteControllerAlertLevelDidChange is 
`NOTIFICATION CENTER - RouteControllerAlertLevelDidChange: Name(_rawValue: RouteControllerAlertLevelDidChange): [AnyHashable("progress"): <MBRouteProgress: 0x170653f80>, AnyHashable("distance"): 20.140475945278673] name = RouteControllerAlertLevelDidChange, object = Optional(<MBRouteController: 0x170469800>), userInfo = Optional([AnyHashable("progress"): <MBRouteProgress: 0x170653f80>, AnyHashable("distance"): 20.140475945278673])
`

While it is clear that this triggers 'around' a value of 20, I can't count on it being the 'arrived' trigger as other updates also trigger this, with various values of distance (I believe these sense approaching corners, etc. - I haven't tested it with lots of corners and turns, but I do get, from a simple one-turn route, the following distance values (approx - no need to type all the number!): 
56.846, 39.3605, 793.1115, 20.1404
Again, where '20.1404.....' is when the voice and direction changes to "you have arrived".

however, no 'alert level' information to know just which type this was (which is what I need to know! :)

2. OK, gotcha - figured it starts to move to 'out of scope' with some of the mods I need (but gotta ask! :)  I'll either move the spec or figure out something else!

3. COOL!  However, please (PLEASE!) give us the ability to move the 'box'!  (I have some other things that 'stack' right on top of the progress line {hint: that is where I put MY cancel button!})

4. I will look forward to it as an option!  In the meantime, what is the 'flip' of the navigation DESIGNED to do?


@1ec5 - THANKS!  I'll look more into the UI flow - I considered a segue, though tried other things first - but from your info and link, I believe I understand enough to get it working.

and, I look forward to the compass fix (or some way to switch it on/off - we don't care about seeing the compass as much as we want the ability to switch it - we can create our own button if we need to!)

**Comment by TCOA** [comment] 2017-05-11 21:09
FYI (after ALL DAY at it....), I found how to get the Alert level, though still not your enumerated words, at least the number....

**Closed** 2018-01-10 20:43 UTC
