### ISSUE TITLE
MapMatching API fails for some routes

### ISSUE THREAD

**Issue by arshadtp** [mapbox/mapbox-navigation-ios#2333] opened 2020-02-05 09:15 UTC
**Mapbox Navigation SDK version:**  
```
 pod 'Mapbox-iOS-SDK', '~> 5.5.0'
 pod 'MapboxNavigation', '~> 0.38.0'
 pod 'MapboxGeocoder.swift', '~> 0.12.0'
```
**MapMatching fails for following:**  
```
 let routeOptions = NavigationMatchOptions(coordinates:routeCoordinates)
 routeOptions.waypoints = routeOptions.waypoints.map({ (wayPoint) -> Waypoint in
     wayPoint.coordinateAccuracy = CLLocationAccuracy(exactly: coordinateAccuracy) ?? wayPoint.coordinateAccuracy
     if wayPoint != routeOptions.waypoints.first && wayPoint != routeOptions.waypoints.last {
            wayPoint.separatesLegs = false
      }
      return wayPoint
 })
 routeOptions.shapeFormat = .polyline6
 Directions.shared.calculateRoutes(matching: routeOptions) { (waypoints, routes, error) in
       // Call back
 }
```

**MapMatching succeeds for the coordinate when using following:**  (Removed  wayPoint.separatesLegs = false)

```
let routeOptions = NavigationMatchOptions(coordinates:routeCoordinates)
routeOptions.waypoints = routeOptions.waypoints.map({ (wayPoint) -> Waypoint in
         wayPoint.coordinateAccuracy = CLLocationAccuracy(exactly: coordinateAccuracy) ?? wayPoint.coordinateAccuracy
            return wayPoint
 })
 routeOptions.shapeFormat = .polyline6
 Directions.shared.calculateRoutes(matching: routeOptions) { (waypoints, routes, error) in
       // Call back
}
```
**Coordinates having issue:**  
`-117.690901,34.378933;-117.6911,34.378881;-117.692502,34.378416;-117.694474,34.378424;-117.69631,34.378287;-117.697426,34.378716;-117.698191,34.37877;-117.69878,34.378347;-117.699452,34.376526;-117.700298,34.375768;-117.700589,34.374709;-117.701098,34.374077;-117.701929,34.37393;-117.702607,34.374233;-117.70288,34.37477;-117.702631,34.375845;-117.703781,34.378184;-117.704495,34.378636;-117.705339,34.378557;-117.705907,34.377959;-117.706469,34.37642;-117.707351,34.375703;-117.707857,34.374781;-117.710444,34.372113;-117.711475,34.372069;-117.71254,34.373073;-117.713348,34.373705;-117.714433,34.373943;-117.717492,34.373945;-117.719162,34.374731;-117.72038,34.375131;-117.722177,34.374687;-117.723086,34.374574;-117.723813,34.374945;-117.724575,34.375674;-117.726189,34.376062;-117.726509,34.376664;-117.726142,34.377622;-117.726426,34.378076;-117.727661,34.378226;-117.72903,34.378981;-117.730026,34.379231;-117.730896,34.378845;-117.731359,34.37743;-117.732102,34.37679;-117.733452,34.376685;-117.734507,34.376349;-117.735693,34.376443;-117.737611,34.375768;-117.739375,34.376336;-117.740615,34.376839;-117.741476,34.3783;-117.742575,34.378556;-117.744104,34.377802;-117.745268,34.377782;-117.746206,34.377526;-117.746417,34.376786;-117.746063,34.375815;-117.746087,34.373386;-117.746796,34.372586;-117.74759,34.372339;-117.749242,34.372551;-117.750569,34.373373;-117.751522,34.373479;-117.752849,34.373231`

**Rest example:**  
***Fails***
[API with waypoints param](https://api.mapbox.com/matching/v5/mapbox/driving/-117.690901,34.378933;-117.6911,34.378881;-117.692502,34.378416;-117.694474,34.378424;-117.69631,34.378287;-117.697426,34.378716;-117.698191,34.37877;-117.69878,34.378347;-117.699452,34.376526;-117.700298,34.375768;-117.700589,34.374709;-117.701098,34.374077;-117.701929,34.37393;-117.702607,34.374233;-117.70288,34.37477;-117.702631,34.375845;-117.703781,34.378184;-117.704495,34.378636;-117.705339,34.378557;-117.705907,34.377959;-117.706469,34.37642;-117.707351,34.375703;-117.707857,34.374781;-117.710444,34.372113;-117.711475,34.372069;-117.71254,34.373073;-117.713348,34.373705;-117.714433,34.373943;-117.717492,34.373945;-117.719162,34.374731;-117.72038,34.375131;-117.722177,34.374687;-117.723086,34.374574;-117.723813,34.374945;-117.724575,34.375674;-117.726189,34.376062;-117.726509,34.376664;-117.726142,34.377622;-117.726426,34.378076;-117.727661,34.378226;-117.72903,34.378981;-117.730026,34.379231;-117.730896,34.378845;-117.731359,34.37743;-117.732102,34.37679;-117.733452,34.376685;-117.734507,34.376349;-117.735693,34.376443;-117.737611,34.375768;-117.739375,34.376336;-117.740615,34.376839;-117.741476,34.3783;-117.742575,34.378556;-117.744104,34.377802;-117.745268,34.377782;-117.746206,34.377526;-117.746417,34.376786;-117.746063,34.375815;-117.746087,34.373386;-117.746796,34.372586;-117.74759,34.372339;-117.749242,34.372551;-117.750569,34.373373;-117.751522,34.373479;-117.752849,34.373231?access_token=ACCESS_TOKEN&waypoints=0;64)

***Succeeds*** (Removed waypoints=0;64 )

[API without waypoints param](https://api.mapbox.com/matching/v5/mapbox/driving/-117.690901,34.378933;-117.6911,34.378881;-117.692502,34.378416;-117.694474,34.378424;-117.69631,34.378287;-117.697426,34.378716;-117.698191,34.37877;-117.69878,34.378347;-117.699452,34.376526;-117.700298,34.375768;-117.700589,34.374709;-117.701098,34.374077;-117.701929,34.37393;-117.702607,34.374233;-117.70288,34.37477;-117.702631,34.375845;-117.703781,34.378184;-117.704495,34.378636;-117.705339,34.378557;-117.705907,34.377959;-117.706469,34.37642;-117.707351,34.375703;-117.707857,34.374781;-117.710444,34.372113;-117.711475,34.372069;-117.71254,34.373073;-117.713348,34.373705;-117.714433,34.373943;-117.717492,34.373945;-117.719162,34.374731;-117.72038,34.375131;-117.722177,34.374687;-117.723086,34.374574;-117.723813,34.374945;-117.724575,34.375674;-117.726189,34.376062;-117.726509,34.376664;-117.726142,34.377622;-117.726426,34.378076;-117.727661,34.378226;-117.72903,34.378981;-117.730026,34.379231;-117.730896,34.378845;-117.731359,34.37743;-117.732102,34.37679;-117.733452,34.376685;-117.734507,34.376349;-117.735693,34.376443;-117.737611,34.375768;-117.739375,34.376336;-117.740615,34.376839;-117.741476,34.3783;-117.742575,34.378556;-117.744104,34.377802;-117.745268,34.377782;-117.746206,34.377526;-117.746417,34.376786;-117.746063,34.375815;-117.746087,34.373386;-117.746796,34.372586;-117.74759,34.372339;-117.749242,34.372551;-117.750569,34.373373;-117.751522,34.373479;-117.752849,34.373231?access_token=ACCESS_TOKEN)

I have tried setting `coordinateAccuracy` to max 50 meters. It is not working.

Also, it looks like creating a map match route for the above coordinates fails in the playground(https://docs.mapbox.com/help/demos/get-started-map-matching-api/index.html). Refer to the screen recording attached  [Google Drive Video](https://drive.google.com/file/d/1YwPSlFB8l32RDbDp0RH1PW7KMcGi2tTT/view?usp=sharing)

**Comment by 1ec5** [comment] 2020-02-06 02:34
As you noted in #2334, I think there is an issue affecting both the Directions API and the Map Matching API. I’m closing this issue in favor of #2334 because I think that issue more clearly demonstrates the root cause. Thanks for both detailed bug reports!

**Closed by 1ec5** 2020-02-06 02:34 UTC
