### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by Ahmeddben** [mapbox/mapbox-navigation-ios#485] opened 2017-08-14 05:32 UTC
Trying to run the sample project followed all steps but when I try to build and run I get the following 2 issues:

Overriding non-open instance method outside of its defining module
and issue 2

Redundant conformance of 'NavigationViewController' to protocole 'PulleyDelegate'

I am using Xcode 8.3.1

Any idea how to solve this and build the project successfully? 

Thanks!

**Comment by frederoni** [comment] 2017-08-14 09:39
Thank you for your report.
This is a duplicate of https://github.com/mapbox/mapbox-navigation-ios/issues/478
CocoaPods approach was fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/480 and there's a [PR #487](https://github.com/mapbox/mapbox-navigation-ios/pull/487) open that fixes this issue when using Carthage.

**Closed by frederoni** 2017-08-14 09:39 UTC

**Comment by Rahul-concetto** [comment] 2018-04-25 13:10
![screen shot 2018-04-25 at 6 39 15 pm](https://user-images.githubusercontent.com/36256933/39247813-075be130-48b8-11e8-9a73-115d3307acd2.png)
I am using Xcode 9.2 and Using Mapbox-iOS-SDK (3.7.0) and Using MapboxNavigation (0.6.0)

**Comment by Rahul-concetto** [comment] 2018-04-25 13:35
i solve with from pod 'MapboxNavigation'  to pod 'MapboxNavigation', '~> 0.16' my pod target is ios 9 so i get error
