### ISSUE TITLE
Installing Mapbox Navigation yields build errors in NavigationMapView.swift

### ISSUE THREAD

**Issue by yoowinks** [mapbox/mapbox-navigation-ios#1643] opened 2018-08-31 02:21 UTC
Hello! As a newbie to Mapbox, I am eager to try this powerful platform but am stuck at the first hurdle.

Simply installing via Cocoapods and adding the import lines per the [documentation guide](https://www.mapbox.com/help/ios-navigation-sdk/#display-user-location), I get the following error when compiling:

<img width="1015" alt="screen shot 2018-08-30 at 9 19 04 pm" src="https://user-images.githubusercontent.com/33309141/44889153-5d983f80-ac9a-11e8-8c7d-b61b1828ba08.png">

Here is my Podfile:
```
target 'MapBoxNavExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapBoxNavExample
  pod 'Mapbox-iOS-SDK', '~> 4.3'
  pod 'MapboxNavigation', '~> 0.19'

end
```

I must add also that if I were to change the Mapbox Navigation version to '~> 0.19.2' and do a _pod repo update_ followed by a _pod install_ I get the following error:

<img width="957" alt="screen shot 2018-08-30 at 9 26 57 pm" src="https://user-images.githubusercontent.com/33309141/44889458-9dabf200-ac9b-11e8-8568-848f846db653.png">

I am using Swift 4.1 in Xcode 9.4.
Can anyone point me in the right direction to resolve this?

**Comment by frederoni** [comment] 2018-08-31 13:52
This is a duplicate of #1607

Try removing the transient dependency on `pod 'Mapbox-iOS-SDK', '~> 4.3'` and let MapboxNavigation pull in a compatible version of the Maps SDK.

**Closed by frederoni** 2018-08-31 13:52 UTC

**Comment by yoowinks** [comment] 2018-09-01 18:48
Thanks @frederoni. I did see the linked case but couldn't understand what the solution was, hence the new case.

I Googled 'remove transient dependency' but nothing I could understand came up. Could you please be more specific on how I remove the dependency on that specific pod?

**Comment by frederoni** [comment] 2018-09-01 23:50
When you specify a specific dependency on `Mapbox-iOS-SDK` in your own Podfile but MapboxNavigation depends on a different version, that's called a transient dependency.

In your case, just remove the `pod 'Mapbox-iOS-SDK', '~> 4.3'` line from your Podfile and run `pod update`.

**Comment by yoowinks** [comment] 2018-09-02 01:39
Brilliant, thank you for the specific steps. 

I had removed that specific line from my Podfile but ran _pod install_ instead of _pod update_. No wonder I was still receiving the same errors. My build has succeeded so onwards I go.

Appreciate your time and help.
