### ISSUE TITLE
Location not updating 

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-navigation-ios#899] opened 2017-11-29 10:06 UTC
Hi,
Location is not updating for `MgMapView.showsUserLocation=false`

it is not calling a method `**mapView(_ mapView: MGLMapView, didUpdate userLocation: MGLUserLocation?)**`.

**Comment by frederoni** [comment] 2017-11-29 12:35
Thanks for reaching out.

Can you explain the issue in a bit more detail?
- What version of the SDK are you using?
- What kind of map view are you using (MGLMapView or NavigationMapView)?
- MapboxCoreNavigation or the drop-in UI MapboxNavigation?

Neither of `MGLMapView` or `NavigationMapView` reports their locations by design.
MGLMapView handles location updates internally and `NavigationMapView`’s location updates are driven by the `RouteController`’s location manager.

**Comment by ashishke2m** [comment] 2017-11-29 14:05
Hi,
I am using simple `MGLMapView` inserted over the UIView.and set the property for the user location.
I used below code to put a map on a view and want an every location updates in **mapView(_ mapView: MGLMapView, didUpdate userLocation: MGLUserLocation?)**.
```
//Map setup
        let localMgMapView = MGLMapView(frame: self.view.frame, styleURL: mapStyleurl)
        localMgMapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        localMgMapView.delegate=self
        localMgMapView.attributionButton.alpha=0
        localMgMapView.compassView.isHidden=true
        localMgMapView.logoView.isHidden=true
        localMgMapView.showsUserLocation=false
      
        self.view.insertSubview(localMgMapView, at: 0)
```

I want to hide current location blue bubble to hide and put a custom annotation instead of it for my current Location.is it something possible?

**Comment by frederoni** [comment] 2017-11-29 15:18
Yes, you can use custom annotation or a custom user location annotation view.
Check out the tutorials and examples on https://www.mapbox.com/ios-sdk/

Closing because this issue is about the Mapbox Maps SDK, not the Mapbox Navigation SDK.

**Closed by frederoni** 2017-11-29 15:18 UTC
