### ISSUE TITLE
Initializing a NavigationViewController without a global API token crashes the app

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#1203] opened 2018-03-06 09:26 UTC
**Mapbox Navigation SDK version:** 0.14.1

Hello!,

Initializing a NavigationViewController with custom styles crashes the application.

https://github.com/mapbox/mapbox-navigation-ios/blob/5d29c1313ecb11ec84088f589f73e5c89494b0aa/MapboxNavigation/NavigationViewController.swift#L236

Initializes the voice controller with an empty token, which in place calls the shared instance of the SpeechSynthesizer (Which crashes without a token)

![image](https://user-images.githubusercontent.com/4553825/37024281-aa73af18-2128-11e8-8005-0101d7a119d5.png)

Possible work around would be to accept a RouteVoiceController on the init 
https://github.com/mapbox/mapbox-navigation-ios/blob/5d29c1313ecb11ec84088f589f73e5c89494b0aa/MapboxNavigation/NavigationViewController.swift#L320

Possible related to https://github.com/mapbox/mapbox-navigation-ios/issues/735

**Comment by bsudekum** [comment] 2018-03-06 16:38
@Sealos thanks for the report, looking into this.

**Comment by 1ec5** [comment] 2018-03-06 17:14
The Mapbox Voice API requires an access token. You can provide it when initializing MapboxVoiceController.

**Comment by 1ec5** [comment] 2018-03-06 17:26
We should probably document somewhere all the places you’d need to set the access token if you don’t set `MGLMapboxAccessToken` in your Info.plist.

**Comment by bsudekum** [comment] 2018-03-06 17:28
@1ec5 don't you think various Mapbox dependencies should be able to find and use this access token if provided? Why leave it up to the developer to do this?

**Comment by 1ec5** [comment] 2018-03-06 17:29
All the dependencies do automatically discover the access token from the Info.plist. The difficulty (possibly by design) comes when the developer wants to make an exception for one or more Mapbox services.

**Comment by JThramer** [comment] 2018-03-06 19:32
@1ec5 we could possibly interrogate the `Info.plist`to see if it already has a value set?

```bash
defaults read $(pwd)/Info.plist "MGLMapboxAccessToken" 
```

**Comment by 1ec5** [comment] 2018-03-06 19:39
@JThramer, that part is already working correctly. If the access token is set in the Info.plist, every library and service honors it. @Sealos is attempting to set the access token for everything _except_ the map SDK. I think we need to know more about the use case before making any changes.

**Comment by Sealos** [comment] 2018-03-07 08:32
> The Mapbox Voice API requires an access token. You can provide it when initializing MapboxVoiceController.

Yes, that's correct, but you're not able to create a NavigationViewController without the default initializer being called, this forces the MapboxVoiceController to use the default instance of the Speech Synthesizer, which crashes.

**Comment by 1ec5** [comment] 2018-03-07 21:26
> you're not able to create a NavigationViewController without the default initializer being called, this forces the MapboxVoiceController to use the default instance of the Speech Synthesizer, which crashes if no token is set on the plist.

This is a problem. Either the voice controller should be created lazily, or there should be an optional access token argument to NavigationViewController’s initializers.

**Comment by JThramer** [comment] 2018-03-08 18:59
With the merge of #1212 I will be closing this ticket as resolved. If you have an objection @Sealos, feel free to re-open.

/cc @bsudekum

**Closed by JThramer** 2018-03-08 18:59 UTC

**Comment by populius** [comment] 2018-08-27 06:38
same problem now with MapboxNavigation (0.19.2)
when initalize NavigationViewController with initWithRoute, immediately called SpeechSynthesizer init method without global access token
![2018-08-27 13 37 45](https://user-images.githubusercontent.com/2752484/44644462-60770400-a9fe-11e8-8bcc-0056a9f397c8.png)
