### ISSUE TITLE
Cancel button should look like a button

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#113] opened 2017-04-05 00:02 UTC
Nothing about the Cancel button’s style makes it look like a button. Black text isn’t supposed to be tappable on iOS. Either the button text should match the application’s tint color, or it should be red (as a destructive action).

![cancel](https://cloud.githubusercontent.com/assets/1231218/24684119/8e340f42-1958-11e7-8a2c-2f9258dc4209.png)

/cc @bsudekum @mayagao

**Comment by pveugen** [comment] 2017-04-05 00:08
Would love to user test this, even just quick and dirty by handing out Voyage to a few (new) users, since I can't believe this is a real usability issue and definitely not a bug.

**Comment by 1ec5** [comment] 2017-04-05 00:13
User testing this library would be great. Should we be testing a public application (since this is a public respository) or an internal application like Voyage? How should we frame the test? There must be plenty of things that deserve user testing, not just this Cancel button, but I’m glad it’s a starting point for this discussion.

**Comment by frederoni** [comment] 2017-09-11 20:09
@1ec5 Can we close this now that #591 has landed?

**Closed** 2017-09-12 18:13 UTC
Labels: topic: design
