### ISSUE TITLE
`InstructionLabel` is not shown on guidance card.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3027] opened 2021-05-24 13:19 UTC
**Mapbox Navigation SDK version:** `2.0.0-beta.10`

### Steps to reproduce

 1. Run example application.
 2. Select `Guidance Card UI` example.
 3. Start active guidance navigation.

### Expected behavior

Guidance card should fully draw `InstructionLabel`.

Looks like current behavior is regression and caused by: https://github.com/mapbox/mapbox-navigation-ios/pull/2977.

### Actual behavior

`InstructionLabel` is empty:

<img width="200" alt="Screen Shot 2021-05-24 at 4 14 20 PM" src="https://user-images.githubusercontent.com/1496498/119353506-d5330780-bc57-11eb-9a97-58b60e205791.png">

/cc @ShanMa1991

**Comment by ShanMa1991** [comment] 2021-05-24 20:35
This problem seems to be caused by the call of `InstructionLabel.instructionDelegate?.label(self, willPresent: instruction, as: attributed) `.

**Comment by ShanMa1991** [comment] 2021-05-24 22:15
When we set the `InstructionLabel.attributedText` from the `InstructionLabel.instructionDelegate?.label(self, willPresent: instruction, as: attributed)`, the `textColor` property is default to white, which is different to the `normalTextColor`. Thus even the `text` of the UILabel is correct, it got hidden by the color.

**Comment by ShanMa1991** [comment] 2021-05-26 21:38
It's fixed in #3028

**Closed by ShanMa1991** 2021-05-26 21:38 UTC
Labels: - bug, UI
