### ISSUE TITLE
Music pauses and does not resume when rerouting occurs

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#2198] opened 2019-07-31 21:47 UTC
**Mapbox Navigation SDK version: 0.32.0 and 0.33.0**

Some of our navigation SDK testers have experienced issues where their actively playing music pauses when they receive new rerouted directions. Their music doesn't resume when the new spoken directions are finished playing. Have there potentially been any regressions around https://github.com/mapbox/mapbox-navigation-ios/issues/391?

When this happens, their audio output stops using the lightening port for output and instead switches to the iPhone speaker.

**Comment by azarovalex** [comment] 2021-03-18 14:50
I can't reproduce this issue on the latest version 1.3.0, seems like it's already fixed.
Since version 0.32 the logic for pausing background music changed a lot. [Current code](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Sources/MapboxNavigation/RouteVoiceController.swift#L167) vs [old code](https://github.com/mapbox/mapbox-navigation-ios/blob/v0.32.0/MapboxNavigation/RouteVoiceController.swift#L164-L193).
So I think we can close this issue.

**Closed** 2021-03-22 13:08 UTC
Labels: - bug, low priority, needs investigation, topic: voice
