### ISSUE TITLE
InstructionsCard orientation & swipe bug

### ISSUE THREAD

**Issue by MarcoCarnevali** [mapbox/mapbox-navigation-ios#2695] opened 2020-10-14 18:07 UTC
Hello, while using the new InstructionsCard view I noticed 2 relevant bugs: 
1. When using navigation on portrait and then change the orientation to landscape this layout issue occur: 

![image_from_ios](https://user-images.githubusercontent.com/9656572/96027764-a39fc580-0e58-11eb-9c76-ae17836ce2ee.png)

2. At the top the second card is visible. I'm not sure if this is a bug or is expected but I'm unable to scroll to see the next card instruction. Seems a weird UX
![image_from_ios-2](https://user-images.githubusercontent.com/9656572/96027848-ccc05600-0e58-11eb-940f-645dc327841b.png)

**Mapbox Navigation SDK version: 1.0.0**

**Comment by jill-cardamon** [comment] 2020-11-02 14:08
Hello, here is an update on the Instruction Card bugs:

1. Landscape layout issue:
    - I have reproduced the issue. It only appears on iOS 14.
    - Still investigating, but I know that the issue is likely related to the card size and animations.

2. Swipe to next card issue:
    - I have reproduced the issue and identified the problem. It only appears on iOS 14.
    - The scroll view will not end dragging due to something going wrong with `snapToIndexPath(..)`: https://github.com/mapbox/mapbox-navigation-ios/blob/b7280efb6cc77eb111a4afd4bd5d956a2bfd3191/MapboxNavigation/InstructionsCardViewController.swift#L247
    - The `snapToIndexPath(..)` function calls `UICollectionView`'s `scrollToItem(at:at:animated:)`, and `scrollToItem(at:at:animated:)` only works when paging is disabled.
    - Found a patch fix by disabling paging, calling `scrollToItem(at:at:animated:)`, and then enabling paging.
    - Other developers are having similar issues with `scrollToItem(at:at:animated:)`, so it could be potentially fixed by an iOS 14 update. We will continue to look for a long-term solution.

**Comment by MarcoCarnevali** [comment] 2020-12-07 14:54
@jill-cardamon is this fixed?

**Comment by jill-cardamon** [comment] 2020-12-07 15:37
@MarcoCarnevali The second bug you reported has been fixed. The first bug is being fixed with #2732.

**Comment by MarcoCarnevali** [comment] 2020-12-07 15:38
Ok, Thanks for the update!

**Comment by truburt** [comment] 2021-02-26 13:44
@jill-cardamon , can this be closed as well?

**Closed** 2021-03-13 01:59 UTC
Labels: - bug, UI, iOS
