### ISSUE TITLE
Navigation crashing on load

### ISSUE THREAD

**Issue by arthurchadRG** [mapbox/mapbox-navigation-ios#2141] opened 2019-05-30 00:25 UTC
Currently using version 0.33.0 of the navigation lib. When the navigation view controller is presented it crashes with the following error:

![image](https://user-images.githubusercontent.com/8038399/58599487-7b58fc00-824e-11e9-85ad-cee9c79cc398.png)

I'm not sure if it's related to the way I had to import the library in my podfile:

```
 pod 'MapboxNavigation', :path => '../mapbox-navigation-ios'
 pod 'MapboxMobileEvents', :modular_headers => true
 pod 'MapboxDirections', :path => '../MapboxDirections.swift', :modular_headers => true
```

I had to import the library this way since I'm still using GooglePlaces library in my code base.

The core mapping functionality seems to work, but every time I try to present the navigation view controller I get the error above.

Here's the code that presents the view controller:

 ```
let origin = Waypoint(coordinate: currentLocation.coordinate, name: "Start Location")
            let destination = Waypoint(coordinate: viewModel.trip.tripDetails.startingLocation.cordinates(), name: "End Location")
            
            let options = NavigationRouteOptions(waypoints: [origin, destination])
            
            
            
            Directions.shared.calculate(options) { (waypoints, routes, error) in
                guard let route = routes?.first else { return }
                
                let viewController = NavigationViewController(for: route)
                self.present(viewController, animated: true, completion: nil)
            }
```

**Comment by frederoni** [comment] 2019-05-31 09:34
I think this is a duplicate of #1017 
Looks like the Nav SDK cannot find the `reroute-sound` file when being linked statically.
Can you try adding `use_frameworks!` in your Podfile or does any library prevent you from doing that?

**Comment by arthurchadRG** [comment] 2019-06-01 14:48
Hi @frederoni,

The google libraries prevent me from doing that unfortunately. Maybe I need to point to the sound file in a different way?

**Comment by arthurchadRG** [comment] 2019-06-08 20:51
**Update**: I solved my particular issue by removing the google places pod and just hitting their API directly. I'm then able to use `use_frameworks!` which fixes the `reroute-sound` issue,

**Comment by frederoni** [comment] 2019-06-10 09:30
The remaining issues to support integrating the Navigation SDK statically with CocoaPods is being tracked https://github.com/mapbox/mapbox-navigation-ios/issues/1017 and https://github.com/mapbox/MapboxDirections.swift/issues/318

**Closed by frederoni** 2019-06-10 09:30 UTC
