### ISSUE TITLE
To add a method to get an user Continuos location in MapboxNavigation delegates to store user actual travelled Route 

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-navigation-ios#856] opened 2017-11-16 06:37 UTC

**Comment by frederoni** [comment] 2017-11-16 09:49
Would you mind explaining the issue in more detail?

**Comment by ashishke2m** [comment] 2017-11-16 09:54
Sometimes mapboxnavigation sdk does not drawing a route on map when actual travelling occurs.
Its not displaying that blue path on map so user will not able to judge navigation properly.

**Comment by frederoni** [comment] 2017-11-16 10:02
Are you using the `NavigationViewController` or the `NavigationMapView` directly? Would you mind sharing the relevant part of your code? We've seen this issue before but not in a recent version. What version of the SDK are you on?

**Comment by ashishke2m** [comment] 2017-11-16 10:29
We are using `NavigationViewController`.
A version of SDK is **0.8.3**

```
var viewController:NavigationViewController
viewController = NavigationViewController(for: route, styles: [CustomStyle()])
navigationController?.present(self.viewController!, animated: true, completion: nil)
```

**Comment by frederoni** [comment] 2017-11-16 10:36
Can you try upgrading to a more recent version? 0.10.0 is already released.

**Comment by ashishke2m** [comment] 2017-11-16 10:47
Actually, we are not using swift 4 right now and we are also facing an issues when updateing it to version 9.0 because we need **mkmapview delegate** `didUpdate` to get continuous location which is not possible with version 9.0 and `NavigationMapView`

**Comment by ashishke2m** [comment] 2017-11-20 05:40
is there any comment for it?

**Comment by bsudekum** [comment] 2017-11-21 16:30
@ashishke2m the easiest way to get constant progress updates is to listen on this notification: https://www.mapbox.com/mapbox-navigation-ios/navigation/0.10.1/Notifications.html#/s:v16MapboxNavigation32RouteControllerProgressDidChangeVCSo14NSNotification4Name

**Comment by frederoni** [comment] 2017-11-21 16:49
Duplicate of #867

**Closed by frederoni** 2017-11-21 16:49 UTC
