### ISSUE TITLE
User Puck Shifted Vertically from true anchor point

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#1651] opened 2018-09-04 23:21 UTC
Hey all,

I've seen/heard a lot of us talk about a hard-to-reproduce issue where the user-puck "shifts" up or down w.r.t. the actual anchor point. Seems like a good idea to go ahead and cut a ticket to start tracking anecdotal stories of reproduction.

Here are my notes from trying to dig into this by breaking in the `NavigationMapView.userAnchorPoint`  computed method:

| Property  | Good Run  | Bad Run |
| ------------- | ------------- | ------------ |
|` contentInset`  | `{116, 0, 80, 0}`  | `{116, 0, 80, 0}` |
| `frame.size`  | `{75, 75}`  | `{75, 75}` |
| `frame.origin` | `{169.11, 454.99}` | `{169.5, 510.5}`|

Feel free to tack onto this ticket as needed.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment] 2018-09-04 23:34
> the user-puck projects in front of the actual anchor point

To clarify, the puck is shifted vertically (sometimes up, sometimes down) from the correct position in the screen coordinate system, irrespective of the route or the map’s rotation.

**Comment by 1ec5** [comment] 2018-09-05 10:05
This issue reproduces consistently in the `carplay` branch, because the safe area insets (akin to the content insets) change shortly after the user puck is first laid out on screen. A fix is in #1653.

Separately, @JThramer discovered while investigating this issue that `MGLMapView.setCamera(_:withDuration:animationTimingFunction:edgePadding:completionHandler:)` doesn’t add `contentInset` to the edge padding, so `NavigationMapView.userAnchorPoint` ends up having to add the edge padding itself: mapbox/mapbox-gl-native#12818.

https://github.com/mapbox/mapbox-navigation-ios/blob/919aa33805f8d191a60642a07d5c082665eeef55/MapboxNavigation/NavigationMapView.swift#L144-L150

**Closed as completed** 2018-09-05 20:22 UTC
Labels: bug, CarPlay
