### ISSUE TITLE
showRoute only shows first 2 legs

### ISSUE THREAD

**Issue by apascual** [mapbox/mapbox-navigation-ios#798] opened 2017-11-06 12:54 UTC
Hi, I am trying to display directions for multiple waypoints in **NavigationMapView** and looks like a part of the directions (the last leg) is not getting presented in the map.

<img width="372" alt="screen shot 2017-11-06 at 13 51 09" src="https://user-images.githubusercontent.com/3491658/32442074-5a592576-c2fa-11e7-9755-d12a8244269a.png">

The legs and steps looks ok:
```
Leg 0
Head east on Kattesund
Continue straight to stay on Kattesund
Turn right onto Stora Södergatan
Turn left onto Västra Mårtensgatan
Make a slight left
Make a slight right
Make a slight left
You have arrived at your 1st destination
Leg 1
Head south
Turn left
Turn left onto Västra Mårtensgatan
Turn right onto Bankgatan
You have arrived at your 2nd destination, on the left
Leg 2
Head north on Bankgatan
Turn right onto Stora Tvärgatan
Turn left onto Råbygatan
Turn right onto Skolgatan
You have arrived at your destination
```

I am using the latest iOS SDK versions:
```
Using Mapbox-iOS-SDK (3.6.4)
Using MapboxCoreNavigation (0.9.0)
Using MapboxDirections.swift (0.10.6)
Using MapboxMobileEvents (0.2.10)
Using MapboxNavigation (0.9.0)
```

Thanks.

**Comment by bsudekum** [comment] 2017-11-06 14:37
Curious, which directions profile are you using?

**Comment by apascual** [comment] 2017-11-06 14:45
@bsudekum I am using "Cycling", but I can also reproduce the issue with "Automobile".

Here is the list of coordinates that I am using:
**1)** 55.702118, 13.190597
**2)** 55.701611, 13.194099
**3)** 55.699075, 13.19603
**4)** 55.700378, 13.201168

**Update:**  Looks like using *RouteOptions* instead of *NavigationRouteOptions* fixes the problem. Is this normal?

**Comment by bsudekum** [comment] 2017-11-06 14:47
You'll definitely want to use `NavigationRouteOptions` when possible. There are a lot of options we turn on in there. Will check this out.

**Comment by bsudekum** [comment] 2017-11-06 15:17
Confirmed, this is a bug.

**Comment by bsudekum** [comment] 2017-11-06 15:24
@apascual a quick fix for this:

```swift
let options = NavigationRouteOptions(waypoints: waypoints)
options.attributeOptions = []
```

`attributeOptions` is used for getting the congestion along a route. But since the biking profile does not support congestion, it's okay to keep this option off.

**Comment by apascual** [comment] 2017-11-06 15:29
@bsudekum Confirmed, that fixed my issue. Thank you :)

**Closed** 2017-11-08 22:12 UTC
Labels: - bug
