### ISSUE TITLE
user heading indicator no update

### ISSUE THREAD

**Issue by pintonos** [mapbox/mapbox-navigation-ios#2218] opened 2019-08-28 16:39 UTC
The user orientation indicator is not updated while navigation. In the meaning of the arrow is always pointing in the direction of the calculated route, but does not turn if the device is turned. Is this not supported now or a bug? User orientation in the normal mapbox map is working fine.

**Comment by 1ec5** [comment] 2019-08-29 06:54
From #2219, I gather that you’re using the navigation SDK with walking directions, but the user puck and map are oriented based on the course (calculated from GPS location updates), which is irrelevant while walking. #2215 fixes this issue so that the puck and map are oriented based on the heading (from the magnetometer).

**Comment by 1ec5** [comment] 2019-08-29 06:55
Duplicate of #1942.

**Closed by 1ec5** 2019-08-29 06:55 UTC
