### ISSUE TITLE
Rerouting Issue in iOS SDK

### ISSUE THREAD

**Issue by soheilnikbin** [mapbox/mapbox-navigation-ios#2272] opened 2019-11-17 06:22 UTC
Navigation keeps on constantly rerouting after every route progress even though the user device location is on the same route. I thought Mapbox automatically handles rerouting only when the user leaves the current route. After I read [this](https://docs.mapbox.com/ios/navigation/overview/rerouting/#off-route-detection) part of the documentation, I thought I needed to handle it manually.

Based on documentation, I used below code to handle rerouting manually but the code is deprecated.

```
func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {
        return navigationViewController.routeController.userIsOnRoute(location)
    }
```
So crash redirects me to this part of Mapbox SDK

```
@available(*, deprecated, renamed: "navigationService", message: "NavigationViewController no longer directly manages a RouteController. See MapboxNavigationService, which contains a protocol-bound reference to the RouteController, for more information.")
/// :nodoc: obsoleted
@objc public final var routeController: RouteController! {
    get {
        fatalError()
    }
    set {
        fatalError()
    }
}
```
but navigationService not containing userIsOnRoute function. Is there an alternative function I could use, or is this a bug?

**Comment by soheilnikbin** [comment] 2019-11-17 09:34
Our team is in rush to release our app within 7 days, so meanwhile we found an alternative solution to at least reduce reroute call.

So we assuming currentStepProgress.distanceRemaining returns distance between device location and end the of current step location in this case we can recognize if driver going to the wrong direction by setting limit to it like below

```
func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {

    return navigationViewController.navigationService.routeProgress.currentLegProgress.currentStepProgress.distanceRemaining > 500
}
```
In this case if distanceRemaining returns more than 500m we assuming driver getting far from actual path and we let SDK to call reroute api to get new route.

BUT PLEASE ANYONE FROM MAPBOX TEAM  give us correct answer since we are a paid user and we rely on mapbox navigation.

**Comment by soheilnikbin** [comment] 2019-11-18 04:23
Ok I found a way to get `userIsOnRoute` function by this line of the code
`navigationViewController.navigationService.router.userIsOnRoute(location)` but It refers to **RouteControllerDataSource** . 

Turns out that there is 2 different `userIsOnRoute` in library one in **RouteControllerDataSource** and another in **RouterDataSource**, there is significant different  between them. 

The one in **RouteControllerDataSource** returns false even though user is on route but the one in **RouterDataSource** is the correct one. Since there is no proper explanation in documentation, can anyone please explain what should I do.

So in the app arrow is on route but it return userIsOnRoute false, this is the code I wrote. Even I delete the code behavior is same.
``` func navigationViewController(_ navigationViewController: NavigationViewController, 
shouldRerouteFrom location: CLLocation) -> Bool {
     return !navigationViewController.navigationService.router.userIsOnRoute(location)
 }

**Comment by avi-c** [comment] 2019-11-18 20:23
@soheilnikbin Do you have a sample project that reproduces the problem that you could share? If you don’t have a whole project, then maybe some of the code you are using?

Finally, can you share a starting/ending coordinate for the original route that is being calculated?

**Comment by soheilnikbin** [comment] 2019-11-20 03:29
Unfortunately I cannot share the entire project here  but I can share the code written for Mapbox navigation as below:

So in this code I'm getting current location of the user to init route and than calling `calculateDirections` to get Navigation Route.

```
  func setupSequences() {
      viewDidLoadSubject
          .flatMapLatest { [weak self] _ -> Observable<CLLocation?> in
              guard let `self` = self else { return .create { _ in return Disposables.create()} }
              self.manager.requestWhenInUseAuthorization()
              self.manager.startUpdatingLocation()
              //
              return self.manager.rx
                  .location
                  .takeUntil(.inclusive, predicate: { $0 != nil })
      }
      .filterNil()
      .flatMapLatest { [weak self] location -> Single<Route> in
          guard let `self` = self else { return .create { _ in return Disposables.create()} }
          self.manager.stopUpdatingLocation()
          return self.calculateDirections(currentLocation: location)
      }
      .subscribe(onNext: routeSubject.onNext)
      .disposed(by: disposeBag)
      //
  }
    
  func calculateDirections(currentLocation: CLLocation) -> Single<Route> {
      let origin = Waypoint(coordinate: CLLocationCoordinate2D(latitude: currentLocation.coordinate.latitude,
                                                                 longitude: currentLocation.coordinate.longitude), name: "Origin")
      //
      let destination = Waypoint(coordinate: CLLocationCoordinate2D(latitude: inProgressJob.location.latitude,
                                                                      longitude: inProgressJob.location.longitude), name: "\(inProgressJob.account.name.fullName)'s Location")
      //
      let options = NavigationRouteOptions(waypoints: [origin, destination])
      options.shapeFormat = RouteShapeFormat.polyline
      options.distanceMeasurementSystem = .metric
      //
      return .create { event in
          Directions.shared.calculate(options) { ( _, routes, error) in
              guard let route = routes?.first, error == nil else {
                  event(.error(error._rlmInferWrappedType()))
                      return
              }
              event(.success(route))
          }
          return Disposables.create()
      }
  }
```   

And then here after getting route to create NavigationViewController. I've tested with simulating `.always`,  `.never` and `.onPoorGPS`. Result was same.

```
viewModel.outputs
            .didGetRoute
            .bind { [weak self] route in
                guard let `self` = self else { return }
                //
                let navigationService = MapboxNavigationService(route: route, simulating: .always)
                let options = NavigationOptions(
                        styles: [CustomNightStyle(), CustomDayStyle()],
                        navigationService: navigationService
                )
                
                //
                let navigationViewController = NavigationViewController(
                    for: route,
                    options: options)
                
                NavigationSettings.shared.distanceUnit = .kilometer
                navigationViewController.route.routeOptions.distanceMeasurementSystem = .metric
                navigationViewController.delegate = self
                //
                self.addChild(navigationViewController)
                self.container.addSubview(navigationViewController.view)
                navigationViewController.view.translatesAutoresizingMaskIntoConstraints = false
                //
                NSLayoutConstraint.activate([
                    navigationViewController.view.leadingAnchor.constraint(equalTo: self.container.leadingAnchor, constant: 0),
                    navigationViewController.view.trailingAnchor.constraint(equalTo: self.container.trailingAnchor, constant: 0),
                    navigationViewController.view.topAnchor.constraint(equalTo: self.container.topAnchor, constant: 0),
                    navigationViewController.view.bottomAnchor.constraint(equalTo: self.container.bottomAnchor, constant: 0)
                ])
                self.didMove(toParent: self)
            }
            .disposed(by: disposeBag)
```
This code tested on this coordinates
Origin | latitude = 3.1554527282714844, longitude = 101.59706281742993
Destination | latitude =  3.1196545760414183, longitude = 101.61728408242021

**Comment by JThramer** [comment] 2019-11-20 18:59
@soheilnikbin:

You can access the function you require using `navigationService.router.userIsOnRoute(_:)`, but this is completely necessary, as this is what the SDK does by default: 

https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L200-L201

**Comment by soheilnikbin** [comment] 2019-11-21 09:16
Great, its working perfectly fine now. 
```
func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {
        return navigationViewController.navigationService.router.userIsOnRoute(location)
    }
```
 This line of the code should clearly mention in documentation, or by default SDK should use `userIsOnRoute` to keep track of device location. If I just remove this function everything goes crazy from the voice command to route.

**Comment by soheilnikbin** [comment] 2019-11-28 14:09
[Problem is still there](https://github.com/mapbox/mapbox-navigation-ios/issues/2240#issuecomment-559507456)

**Comment by 1ec5** [comment] 2020-01-07 21:23
This is a duplicate of #2125. You’re setting `options.shapeFormat = RouteShapeFormat.polyline`, which is supported when using LegacyRouteController, but RouteController relies on MapboxNavigationNative, which only supports the `polyline6` shape format. Leaving `shapeFormat` set to the default shape format should be a suitable workaround for now. It doesn’t affect the coordinates that you access via `Route.coordinates` or `RouteStep.coordinates`.

**Closed by 1ec5** 2020-01-07 21:23 UTC
