### ISSUE TITLE
[Bug]: Invalid Privacy Manifest

### ISSUE THREAD

**Issue by ir-fuel** [mapbox/mapbox-navigation-ios#4615] opened 2024-03-14 09:18 UTC
### Mapbox Navigation SDK version

2.17.0

### Steps to reproduce

Submit an app built with MapboxNavigation 2.17.0 to the App Store

### Expected behavior

Nothing should be reported by Apple

### Actual behavior

Apple reports the following:

ITMS-91056: Invalid privacy manifest

The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy”. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment] 2024-04-02 15:45
Hi @ir-fuel

Thank you for reporting the issue. The version with the fix will be available soon, we expect to have the compatible [Maps SDK version this week](https://github.com/mapbox/mapbox-maps-ios/issues/2145#issuecomment-2025506111).

**Comment by jkgz** [comment] 2024-04-12 17:41
Hi @kried 

Is there still a pending release that includes a privacy manifest update for the Navigation SDK? I updated the Maps SDK to 10.17.0 as mentioned in your linked thread, which fixed the invalid privacy manifest warning, but am still getting a report from Apple: 

Your app’s code in the “VAMOS” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

Based on a binary scan, it looks like there are calls to fstat, stat, etc in MapboxNavigationNative.framework which are mentioned in Apple's link as usages of NSPrivacyAccessedAPICategoryFileTimestamp

Thanks for any info!

**Comment by azarovalex** [comment] 2024-04-15 09:30
Hello @jkgz.

`MapboxNavigationNative.framework` is a dynamic library that is not linked in your main executable "VAMOS", so if Apple highlights this file it means something else is triggering the warning. 
Could you let me know which SDK versions you are using right now and which package manager?

**Comment by jkgz** [comment] 2024-04-16 18:02
Hi @azarovalex 

I apologize if I was misleading in my post about what Apple mentioned in the warning. Apple only mentioned API usage of NSPrivacyAccessedAPICategoryFileTimestamp. I mentioned MapboxNavigation.framework based on a binary scanner others had posted elsewhere to detect API usage in libraries, but I think that was just confusing and incomplete info.

It looks like the issue is resolved for me now. We had a package reference to an old version of MapboxSearch which we are not actually using. When I removed that package, I saw the binary scanner no longer included fstat and stat as associated with my binary, and on submit to AppStore Connect, it looks like nothing is flagged. Thanks for your attention.

**Comment by azarovalex** [comment] 2024-04-16 18:52
@jkgz good to hear your problem is resolved!

Full disclosure: `MapboxNavigationNative.framework` **_does_** use these API, so the scanner you mentioned indeed works, but fortunately for us Apple doesn't enforce privacy manifests for all 3rd party libraries, there is only [a small list of them](https://developer.apple.com/support/third-party-SDK-requirements/).
I'm going to close the issue based on the fact that the NavSDK sample I submitted didn't trigger any warnings. We'll update MapboxNavigationNative.framework with the manifest in future releases, and latest versions of `MapboxCommon.framework` and `MapboxCoreMaps.framework` already include manifests.

**Closed by azarovalex** 2024-04-16 18:52 UTC
Labels: bug
